testing new pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,4 +4,13 @@
 
 # npx lint-staged --debug
 
-npm run pretty-quick --staged && npm run lint
+for file in $(git --diff-filter=d --cached --name-only | grep -E '\.(ts|html)$')
+do
+  git show ":$file" | npm run pretty-quick --staged && npm run lint --stdin --stdin-filename "$file" # we only want to lint the staged changes, not any un-staged changes
+  if [ $? -ne 0 ]; then
+    echo "ESLint failed on staged file '$file'. Please check your code and try again. You can run ESLint manually via npm run eslint."
+    exit 1 # exit with failure status
+  fi
+done
+
+# npm run pretty-quick --staged && npm run lint
